114: EMF generator generations fails
eclipse-emfcloud/ecore-glsp pull request #118
Opened 2021-12-07 08:17 UTC by CamilleLetavernier

- Fix the backend product configuration

There is still an issue with the code generator: it only works once. There are several causes (yet to be investigated):

- EMF Code is generated as an Eclipse Project, with associated metadata (.metadata/, .project). If the .project is removed, the project becomes invalid and the generation will fail (Workaround: also delete .metadata/ to start on a clean Eclipse Workspace)
- If the .metadata/.project are still present, the generator fails with a NPE

This is mostly related to this old issue from the archived repo: https://github.com/eclipse-emfcloud/ecore-glsp/issues/117

It would make it easier to separate the Backend/EMF Workspace from the Theia Workspace, and that would cause less interferences

2021-12-07 15:10 UTC, CamilleLetavernier commented
The new commit fixes the instabilities with Codegen, and improves the UI (added a context menu on *.genmodel files to trigger the generation, clarified some parameters, ...)

2021-12-07 16:35 UTC, ndoschek requested changes
Thanks Camille! The genmodel generation works great for me, also the additional descriptions in the quick input field are a good improvement.

Regarding the code generation:
- If I trigger the the code generation on a newly created genmodel, the `src` folder is created outside the model folder in my case (pls see the attached screenshot). I assume this should be located inside the model folder, right?

![image](https://user-images.githubusercontent.com/47414588/145068320-e51fdceb-8185-4c6c-814c-b9b83c516125.png)
- Also, the files in the generated `src` folder are not listed in `.gitignore` - should we add the generated sources folder here?


One other question regarding the codegen backend app:
I tried to start the `org.eclipse.emfcloud.ecore.codegen.product` but I get the following error. Did I miss something here or are there additional settings needed? If so, it would be great if we could offer a launch config as for the `Ecore-GLSP App`.
```
!ENTRY org.eclipse.osgi 4 0 2021-12-07 17:33:22.988
!MESSAGE Application error
!STACK 1
java.lang.IllegalArgumentException: Expected argument: genmodel path; got []
	at org.eclipse.emfcloud.ecore.backend.app.CodegenApplication.start(CodegenApplication.java:38)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)
```

2021-12-08 08:02 UTC, CamilleLetavernier commented
> If I trigger the the code generation on a newly created genmodel, the src folder is created outside the model folder in my case (pls see the attached screenshot). I assume this should be located inside the model folder, right?

I changed it to a path relative to the Theia workspace; so it's now more consistent with how it works in Eclipse. The expected genmodel path is <project>/<src>/. We need to include the project, because GenModel can generate 4 different projects/plug-ins (Although we only support one at the moment): Java, Edit/Editor, and Tests. Each project uses its own path.

So, if you only specify `src`, it assumes that "src" is the target project, and will create it at the root of the workspace (That's why I clarified the descriptions of the parameters :D )

> Also, the files in the generated src folder are not listed in .gitignore - should we add the generated sources folder here?

For the example workspace, yes; it would make sense. However... I'm not sure what to add in the .gitignore. I usually don't commit anything from the workspace. Excluding src/ might be too much (why src/ and not src-gen/ ?). And if a users want to play with the tool a bit, it could be confusing to see some changes (ecore, genmodel) and not others (generated java code). So I'm not really sure I want to change anything in the gitignore.

> One other question regarding the codegen backend app:
I tried to start the org.eclipse.emfcloud.ecore.codegen.product but I get the following error. Did I miss something here or are there additional settings needed?

We don't use this product like the other ones. It is copied to the Theia backend during build (`theia-ecore/build`), and Theia can start it directly when Codegen is triggered (With the appropriate arguments). We want to merge it with the Modelserver at some point (Add 3 new endpoints there, for Ecore/GenModel/Codegen), but that will be covered in #117 (Sometime :) )

Until then, this application is not meant to be manually started; it's started via `EcoreFileGenServer` in `ecore-file-generation.ts`. It starts, executes codegen (or file creation), and then stops again.

2021-12-08 08:04 UTC, CamilleLetavernier commented
fixes #13 fixes #12

2021-12-09 08:24 UTC, ndoschek commented
> > If I trigger the the code generation on a newly created genmodel, the src folder is created outside the model folder in my case (pls see the attached screenshot). I assume this should be located inside the model folder, right?
> 
> I changed it to a path relative to the Theia workspace; so it's now more consistent with how it works in Eclipse. The expected genmodel path is //. We need to include the project, because GenModel can generate 4 different projects/plug-ins (Although we only support one at the moment): Java, Edit/Editor, and Tests. Each project uses its own path.
> 
> So, if you only specify `src`, it assumes that "src" is the target project, and will create it at the root of the workspace (That's why I clarified the descriptions of the parameters :D )

Oh I see, if using the entry `Generate EMF Generator Model...` everything is described very well and behaves accordingly :+1: 
I still think if the genmodel is generated via the entry `Generate EMF Generator Model` without user options, it would be great if the default code gen path would be set to `statemachine/model/src` for example, instead of only `src`. I checked how it is done in Eclipse, and there they use the genmodel path and add the `src` directory to that path by default in my case.


> For the example workspace, yes; it would make sense. However... I'm not sure what to add in the .gitignore. I usually don't commit anything from the workspace. Excluding src/ might be too much (why src/ and not src-gen/ ?). And if a users want to play with the tool a bit, it could be confusing to see some changes (ecore, genmodel) and not others (generated java code). So I'm not really sure I want to change anything in the gitignore.

Ah you're right, thats true of course - then I'll agree to leave it like that.

> We don't use this product like the other ones. It is copied to the Theia backend during build (`theia-ecore/build`), and Theia can start it directly when Codegen is triggered (With the appropriate arguments). We want to merge it with the Modelserver at some point (Add 3 new endpoints there, for Ecore/GenModel/Codegen), but that will be covered in #117 (Sometime :) )
> 
> Until then, this application is not meant to be manually started; it's started via `EcoreFileGenServer` in `ecore-file-generation.ts`. It starts, executes codegen (or file creation), and then stops again.

Alright, that's fine then for me then :)

2021-12-09 08:42 UTC, CamilleLetavernier commented
> I still think if the genmodel is generated via the entry `Generate EMF Generator Model` without user options, it would be great if the default code gen path would be set to `statemachine/model/src` for example, instead of only `src`. I checked how it is done in Eclipse, and there they use the genmodel path and add the `src` directory to that path by default in my case.

Ah! I knew I was missing something, but I couldn't figure out what :) Indeed, the parameter-less version needs to be updated with a more appropriate value. I'll push an update.

2022-01-05 11:53 UTC, CamilleLetavernier commented
I've updated the PR to use a better default value for the Java source folder. It currently takes the root project, and appends src-gen/

So if your model is located in:

`~/myproject/models/myModel/example.ecore`

The java source folder will be

`~/myproject/src-gen/`

2022-01-18 09:47 UTC, ndoschek approved these changes
Thanks for the update Camille, looks great to me! :tada:

2022-01-18 09:54 UTC, merged

2022-02-03 08:29 UTC, jmini commented on server/org.eclipse.emfcloud.ecore.backend-app/org.eclipse.emfcloud.ecore.codegen.product/org.eclipse.emfcloud.ecore.codegen.product
> +      <plugin id="org.apache.felix.scr" autoStart="true" startLevel="2" />
This is relevant to solve the NPE described in #114

```
Caused by: java.lang.NullPointerException
at org.eclipse.core.internal.resources.CharsetDeltaJob.startup(CharsetDeltaJob.java:212)
at org.eclipse.core.internal.resources.CharsetManager.startup(CharsetManager.java:505)
at org.eclipse.core.internal.resources.Workspace.startup(Workspace.java:2484)
at org.eclipse.core.internal.resources.Workspace.open(Workspace.java:2231)
```